INFO:myproject:request.remote_addr: 127.0.0.1
INFO:myproject:request.environ.get('REMOTE_ADDR'): 127.0.0.1
INFO:myproject:request.environ.get('HTTP_X_FORWARDED_FOR'): 118.70.184.68
ERROR:myproject:Exception on / [GET]
Traceback (most recent call last):
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:myproject:request.remote_addr: 127.0.0.1
INFO:myproject:request.environ.get('REMOTE_ADDR'): 127.0.0.1
INFO:myproject:request.environ.get('HTTP_X_FORWARDED_FOR'): 118.70.184.68
ERROR:myproject:Exception on / [GET]
Traceback (most recent call last):
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:myproject:request.remote_addr: 127.0.0.1
INFO:myproject:request.environ.get('REMOTE_ADDR'): 127.0.0.1
INFO:myproject:request.environ.get('HTTP_X_FORWARDED_FOR'): 118.70.184.68
ERROR:myproject:Exception on / [GET]
Traceback (most recent call last):
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/mrxcnh/.pyenv/versions/3.6.6/envs/flake8-env/lib/python3.6/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:myproject:request.remote_addr: 127.0.0.1
INFO:myproject:request.environ.get('REMOTE_ADDR'): 127.0.0.1
INFO:myproject:request.environ.get('HTTP_X_FORWARDED_FOR'): 118.70.184.68
2020-11-11 11:33:20 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:33:20 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:33:20 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 118.70.184.68
2020-11-11 11:34:11 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:1f00:8001:1ea::
2020-11-11 11:34:11 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:1f00:8001:257::
2020-11-11 11:34:11 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:34:11 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:800:610d:5710:4938:abaf:fc77:b09d


2020-11-11 11:35:20 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:35:20 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:35:20 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:800:610d:5710:4938:abaf:fc77:b09d
2020-11-11 11:36:10 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:36:10 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:36:10 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:800:610d:5710:4938:abaf:fc77:b09d
2020-11-11 11:36:51 INFO     request.remote_addr: 127.0.0.1
2020-11-11 11:36:51 INFO     request.environ.get('REMOTE_ADDR'): 127.0.0.1
2020-11-11 11:36:51 INFO     request.environ.get('HTTP_X_FORWARDED_FOR'): 2402:800:610d:5710:4938:abaf:fc77:b09d
